"""add account_id unique constraint

Revision ID: 1d9d365b098c
Revises: e06669b368dd
Create Date: 2026-09-17 17:35:23.270115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d9d365b098c'
down_revision: Union[str, Sequence[str], None] = 'e06669b368dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_account_id_discord_id', 'discord_users', ['account_id', 'discord_id'])
    op.create_unique_constraint('uix_account_id_node_id', 'unlocks', ['account_id', 'node_id'])
    op.create_unique_constraint('uix_steam_id', 'wardog_accounts', ['steam_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_steam_id', 'wardog_accounts', type_='unique')
    op.drop_constraint('uix_account_id_node_id', 'unlocks', type_='unique')
    op.drop_constraint('uix_account_id_discord_id', 'discord_users', type_='unique')
    # ### end Alembic commands ###
