"""add discord roles

Revision ID: b639b7b951cb
Revises: 1d9d365b098c
Create Date: 2026-09-25 19:45:08.702330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b639b7b951cb'
down_revision: Union[str, Sequence[str], None] = '1d9d365b098c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_role_groups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discord_roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('discord_role_group_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tracked_item', sa.String(), nullable=False),
    sa.Column('role_range_min', sa.Integer(), nullable=False),
    sa.Column('role_range_max', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discord_role_group_id'], ['discord_role_groups.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', 'discord_role_group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discord_roles')
    op.drop_table('discord_role_groups')
    # ### end Alembic commands ###
