"""add discord server info

Revision ID: d77e52f32a43
Revises: 518b6eeb9d6d
Create Date: 2026-09-26 11:45:44.888476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77e52f32a43'
down_revision: Union[str, Sequence[str], None] = '518b6eeb9d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_settings',
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('server_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('server_id')
    )
    op.add_column('discord_role_groups', sa.Column('guild_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'discord_role_groups', 'server_settings', ['guild_id'], ['server_id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'discord_role_groups', type_='foreignkey')
    op.drop_column('discord_role_groups', 'guild_id')
    op.drop_table('server_settings')
    # ### end Alembic commands ###
