"""create initial tables

Revision ID: e06669b368dd
Revises: 44d25f897197
Create Date: 2026-09-17 16:55:58.367857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e06669b368dd'
down_revision: Union[str, Sequence[str], None] = '44d25f897197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discord_users', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discord_users', 'display_name')
    # ### end Alembic commands ###
