"""create initial tables

Revision ID: f8e78748a2aa
Revises: 
Create Date: 2026-09-16 19:23:45.843723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e78748a2aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wardog_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('steam_id', sa.String(), nullable=False),
    sa.Column('wardogs_player_id', sa.String(), nullable=False),
    sa.Column('social_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('discriminator', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discord_users',
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['wardog_accounts.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('discord_id')
    )
    op.create_table('stats_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('player_data_version', sa.BigInteger(), nullable=True),
    sa.Column('wardog_level', sa.BigInteger(), nullable=False),
    sa.Column('infantry_level', sa.BigInteger(), nullable=False),
    sa.Column('infantry_xp', sa.BigInteger(), nullable=False),
    sa.Column('medic_level', sa.BigInteger(), nullable=False),
    sa.Column('medic_xp', sa.BigInteger(), nullable=False),
    sa.Column('recon_level', sa.BigInteger(), nullable=False),
    sa.Column('recon_xp', sa.BigInteger(), nullable=False),
    sa.Column('support_level', sa.BigInteger(), nullable=False),
    sa.Column('support_xp', sa.BigInteger(), nullable=False),
    sa.Column('driver_level', sa.BigInteger(), nullable=False),
    sa.Column('driver_xp', sa.BigInteger(), nullable=False),
    sa.Column('pilot_level', sa.BigInteger(), nullable=False),
    sa.Column('pilot_xp', sa.BigInteger(), nullable=False),
    sa.Column('cash', sa.BigInteger(), nullable=False),
    sa.Column('gold', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['wardog_accounts.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unlocks',
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['wardog_accounts.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('account_id', 'node_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unlocks')
    op.drop_table('stats_snapshots')
    op.drop_table('discord_users')
    op.drop_table('wardog_accounts')
    # ### end Alembic commands ###
